language: android

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

sudo: false

cache:
  directories:
    - $HOME/.m2

script:
  ./gradlew build
